name: dart_academia_flutter
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies:
  path: ^1.8.0
  http: ^0.13.4
  mysql1: ^0.19.2
  internet_connection_checker: ^0.0.1+3
  socket_io_client: ^1.0.2
  
dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
